---
version: "3.3"

services:
  inbox:
    build: ./
    env_file:
      - ./.env.local
    ports:
      - "3004:3004"
      - "25:25"
    links:
      - elastic
    depends_on:
      - elastic
    restart: always
    volumes:
      - attachments:/app/attachments

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - discovery.type=single-node
    restart: always
    volumes:
      - data:/usr/share/elasticsearch/data

volumes:
  data:
    driver: local
  attachments:
    driver: local
