---
version: "3.3"

services:
  modules:
    image: node:14.17.6-alpine3.13
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    command: sh -c "npm i"
    working_dir: /app
    profiles: ["modules"]
  app:
    image: node:14.17.6-alpine3.13
    environment:
      - INIT=${INIT}
      - NODE_ENV=${NODE_ENV}
    ports:
      - "3004:3004"
      - "3000:3000"
      - "25:25"
    links:
      - elastic
    depends_on:
      - modules
      - elastic
    restart: always
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    command: sh -c "npm run ${NODE_ENV}"
    working_dir: /app
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - discovery.type=single-node
    restart: always
    volumes:
      - data:/usr/share/elasticsearch/data

volumes:
  data:
    driver: local
  node_modules:
